### ISSUE TITLE
Add options for initialising a project

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [sebastianpopp/git-ftp-action#2]
The action only works for deploying once git-ftp is deployed.
If the project hasn't been initialised with `git ftp init` or `git ftp catchup`
Would be good to allow these options through this action so the repos don't need to be manually initialised

**Comment by sebastianpopp** [comment]
There's an `--auto-init` option in [Version 1.3.3](https://github.com/git-ftp/git-ftp/blob/master/CHANGELOG.md#version-133). I'll soon rewrite the action to use that, but right now the latest version in the package repo for debian stretch is [1.3.1](https://packages.debian.org/stretch/git-ftp), so git-ftp needs to be installed manually in the docker container.

**Comment by sebastianpopp** [comment]
The action is now using the `--auto-init` option, so there're no additional options necessary.
