### ISSUE TITLE
exclude a file?

### ISSUE THREAD

**Issue by saltnpixels** [sebastianpopp/git-ftp-action#5]
Very cool workflow

How can i exclude the github file from being deployed?

**Comment by sebastianpopp** [comment]
git-ftp allows you to exclude files and directories by adding a `.git-ftp-ignore` file to you repository. Check the [git-ftp manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#ignoring-files-to-be-synced) for more information on that.

**Comment by saltnpixels** [comment]
Thanks.
