### ISSUE TITLE
@ sign in username

### ISSUE THREAD

**Issue by andrewbarnesweb** [sebastianpopp/git-ftp-action#7]
I can't be sure, but I'm struggling to get this work. And wondered if it's because I have an `@` sign in my username. I'm using CPanel and it adds in @ signs for annoying reasons.

When it errors out, the @ sign seems to have been escaped as below?

![image](https://user-images.githubusercontent.com/20924669/71322925-0472a180-24c5-11ea-939a-8e08897dd209.png)

**Comment by sebastianpopp** [comment]
I have no way to test that right now. Did you try to install git-ftp locally and run the command manually? I think escaping the username should be ok, so it doesn't become part of your password.

**Comment by andrewbarnesweb** [comment]
I'll give `git-ftp` a try locally. :-) 

Just tried my credentials in Filezilla and I'm getting a certificate mismatch warning that I have to 'OK'. Wonder if that could be holding it up?

**Comment by andrewbarnesweb** [comment]
`git-ftp` I can't get to connect whatever I seem to try. Just times out trying to do the SSL part.

![image](https://user-images.githubusercontent.com/20924669/71326375-c3dd4d00-24f1-11ea-93af-8708e9aec386.png)

**Comment by andrewbarnesweb** [comment]
Regardless, not an issue with this repo. So I'll close :-). Thanks for your help.

**Comment by sebastianpopp** [comment]
did you try adding the ’--insecure’ flag?

**Comment by andrewbarnesweb** [comment]
Yeah. That just made it seem to hang for approx 5 minutes and then give up with that error :-(
