### ISSUE TITLE
Unknown SHA1 object

### ISSUE THREAD

**Issue by c-tanner** [sebastianpopp/git-ftp-action#9]
Trying to implement this into our workflow but receiving the `Unknown SHA1 object` error when running checks. Everything is in sync between the local / remote repos (git-ftp.log hash on remote matches latest commit hash).

Any thoughts?

**Comment by sebastianpopp** [comment]
Did you try to run the command on your local machine? I sometimes run into the same error especially when first setting this up and running it locally usually solves this. Otherwise, maybe try `catchup` from your local machine.

**Comment by matteogiacobazzi** [comment]
Same problem here. I've initialized the remote server from my local machine with a `catchup` and from my local machine everything works fine, but adding the Action in github I got the error.

**Comment by c-tanner** [comment]
@sebastianpopp Yes, running an ftp push locally works as expected, but whenever it's run as an action it fails. I've run the checks a few times, sometimes right after running a push locally, and sometimes after waiting a bit after a local push, but still receive the error.

**Comment by sebastianpopp** [comment]
Any chance you're using `actions/checkout@v2` to check out your repo? I just had the same issue with v2, which was solved by going back to `actions/checkout@v1` for now. Not sure yet why v2 doesn't work.

**Comment by matteogiacobazzi** [comment]
Yes, I confirm that also in my case going back to `actions/checkout@v1` solved the issue. Thanks!

**Comment by c-tanner** [comment]
Yep, that seemed to do it. The version I was using was using `checkout@master` for whatever reason. Thanks for the assist!

**Comment by steinbrueckri** [comment]
Link issue https://github.com/git-ftp/git-ftp/issues/417

**Comment by sebastianpopp** [comment]
The action is already adding the `syncroot` setting by default, so I don't think that's it. I think the new version of the `checkout`-action is not getting the whole list of changes. At least that's what I interpret of the Changelog saying

> [The default behavior now fetches only the SHA being checked-out](https://github.com/actions/checkout/blob/master/CHANGELOG.md)

**Comment by steinbrueckri** [comment]
As I know the v2 from Checkout Support a checkout fetch-depth and the default is 1. Maybe this solves the behavior. 

Br Richard
